apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: bepr27gny-python 
  janus-idp.io/tekton: bepr27gny-python
  backstage.io/kubernetes-id: bepr27gny-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bepr27gny-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml